config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns (
    path('admin/', admin.site.urls),
    path('', include('online_shop.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('rosetta/', include('rosetta.urls')),
    # path('i18n/', include('django.conf.urls.i18n'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_shop/urls.py
from django.urls import path
from online_shop.views.views import update_quantity, remove_item, add_multiple_to_cart, ProductListView, product_detail, CategoryListView, add_to_cart, cart_page, CategoryDetailView
from online_shop.views import views
from online_shop.views.auth import (account, LoginPage, CustomLogoutView, RegisterPage, update_account, ForgotPasswordPage, activate_account, ActivateEmailView, reset_password, CustomResetPasswordConfirmView,forgot_password)


app_name = 'online_store'

urlpatterns = [
    path('', ProductListView.as_view(), name='index_page'),
    
    path('product/<int:pk>/edit/', views.edit_product, name='edit_product'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
    path('product/<int:pk>/confirm-delete/', views.confirm_delete, name='confirm_delete_product'),
    
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='categories_detail'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('product/<int:pk>/<slug:slug>/', product_detail, name='product_detail'),

    # path('add-to-cart/<int:product_id>/', cart_view, name='add_to_cart'),
    path('account/', account, name='account'),

    path('cart/', cart_page, name='cart_page'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/update/<int:item_id>/', update_quantity, name='update_quantity'),
    path('cart/remove/<int:item_id>/', remove_item, name='remove_item'),
    path("add-multiple-to-cart/", add_multiple_to_cart, name="add_multiple_to_cart"),
    path('checkout/', views.go_to_checkout, name='checkout'),

    # auth 
    path('registration/', RegisterPage.as_view(), name="registration"),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout_page'),
    path('update_account/', update_account, name='update_account'),

    # password reset
    path('forgot-password/', ForgotPasswordPage.as_view(), name='forgot_password'),
    path('activate/<str:uid>/<str:token>', ActivateEmailView.as_view(), name='confirm_mail'),
    path('reset-password/', reset_password, name='reset_password'),

]

templates/components/base.html
{% load static %}  <!-- Load static files -->
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Online Store{% endblock %}</title>  <!-- Static title -->

    <!-- Styles -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="{% static 'online_shop/css/styles.css' %}"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=shopping_cart" />
</head>
<body class="d-flex flex-column">
    
    <!-- Navbar (Fixed) -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'online_store:index_page' %}">Online Store</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'online_store:cart_page' %}">
                            <i class="bi bi-cart4"></i> {% trans "My Cart" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'online_store:account' %}">
                            <i class="bi bi-person"></i> {% trans "Account" %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'online_store:registration' %}">
                            <i class="bi bi-person-plus me-2"></i> {% trans "Register" %}
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'online_store:categories' %}">
                            <i class="bi bi-layers-fill"></i> {% trans "Categories" %}
                        </a>
                    </li>
                </ul>

                <!-- Search -->
                <form method="GET" action="{% url 'online_store:index_page' %}" class="d-flex">
                    <input class="form-control me-2" type="search" name="search" placeholder="Search" value="{{ request.GET.search }}">
                </form>

                <!-- Login/Logout -->
                {% if user.is_authenticated %}
                <form action="{% url 'online_store:logout_page' %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-light ms-2">{% trans "Logout" %}</button>
                </form>
                {% else %}
                <a class="btn btn-outline-light ms-2" href="{% url 'online_store:registration' %}">{% trans "Login / Register" }%</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.min.js"></script>
    {% block scripts %}
    <script defer>
        document.addEventListener("DOMContentLoaded", function () {
            document.querySelectorAll(".add-to-cart-btn").forEach(button => {
                button.addEventListener("click", function () {
                    let productId = this.getAttribute("data-product-id");
                    let form = document.querySelector(`#add-to-cart-form-${productId}`);
                    if (form) {
                        console.log(`Submitting form for product ID: ${productId}`);
                        form.submit();
                    } else {
                        console.log("Form not found");
                    }
                });
            });
        });
    </script>
    {% endblock %}
</body>
</html>

templates/components/pagination.html
<ul class="pagination">
    {% for page in page_obj.paginator.page_range %}
        {% if page == page_obj.number %}
            <li class="page-item active">
                <a class="page-link bg-dark text-white border-0">{{ page }}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link text-dark" href="?page={{ page }}">{{ page }}</a>
            </li>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link text-dark" href="?page={{ page_obj.next_page_number }}" arial-label="Next">
                <span aria-hidden="true"></span>&raquo;
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link text-dark" arie-hidden="true">&raquo;</span>
        </li>
    {% endif %}
</ul>